#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
#  بدون اسم.py
#  
#  Copyright 2023 zerrouki <zerrouki@majd4>
#  
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#  
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#  
#  
"""
Extract Frequent stopwords from Tashkeela corpus

Input: A file of words and their frequency extracted from Tashkeel Corpus

Ouput: a List of stopwords and their frequency 
"""

from pprint import pprint
import arabicstopwords.arabicstopwords as stper
import argparse
def grabargs():
    parser = argparse.ArgumentParser(description='Extract most frequent stopwords from  a corpus.')
    # add file name to import and filename to export
    
    parser.add_argument("-f", dest="filename", required=True,
    help="input file to convert", metavar="FILE")
   
    args = parser.parse_args()
    return args

def main(args):
    args = grabargs()
    #~ filename, outputformat,  allforms, version=grabargs()
    filename = args.filename    
    try:
        fl = open(filename, encoding="utf8")
    except:
        sys.exit("can't opne file "+filename)
    
    else:

        lines = fl.readlines()
        # the file is generated by uniq command, a frequncy and a word
        # file contains extra spaces used to align fequency and words
        # clean lines, strip extra spaces
        lines = [ln.strip() for ln in lines]
        # split lines into fields, separator is a space
        # avoid empty lines
        lines = [ln.split(" ") for ln in lines if ln]
        # avoid lines with less then two fields
        lines = [ln for ln in lines if len(ln)>=2]
        # filter lines if a word is a stopword
        lines = [ln for ln in lines if stper.is_stop(ln[1])] 
        for line in lines:
            print("\t".join([
            line[1],
            line[0]
            ]))      

    return 0

if __name__ == '__main__':
    import sys
    sys.exit(main(sys.argv))
