--#*************************************
--Arabic Stop word list for morphology analysis and information retrival
--Version        : 0.9
--Generated at   : 2023/02/02:08:53 
--Author         : Taha Zerrouki
--Web            : http://arabicstopwords.sf.net
--Source         : http://github.com/linuxscout/arabicstopwords
--*************************************
create TABLE classedstopwords
                (
                ID INT UNIQUE NOT NULL, 
                WORD TEXT NOT NULL, 
                vocalized TEXT NOT NULL, 
                word_type TEXT NOT NULL,

                word_class TEXT NOT NULL,
                conjonction tinyint(1) default 0, 
                definition tinyint(1) default 0,  
                preposition tinyint(1) default 0,

                pronoun tinyint(1) default 0, 
                interrog tinyint(1) default 0,
                conjugation tinyint(1) default 0,                     
                qasam tinyint(1) default 0,
                
                defined tinyint(1) default 0,
                is_inflected  int(1) default 0,
                tanwin int(1) default 0,
                action varchar(10) default '', 

                object_type  varchar(10) default '',
                need  varchar(10) default ''                
                );
            
insert into classedstopwords values (1, 'أن', 'أَنَّ', 'حرف', 'إن و أخواتها', 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 'ناصب', 'اسم', '');
insert into classedstopwords values (2, 'إن', 'إِنَّ', 'حرف', 'إن و أخواتها', 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 'ناصب', 'اسم', '');
insert into classedstopwords values (3, 'عل', 'عَلًّ', 'حرف', 'إن و أخواتها', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'ناصب', 'اسم', '');
insert into classedstopwords values (4, 'كأن', 'كَأَنَّ', 'حرف', 'إن و أخواتها', 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 'ناصب', 'اسم', '');
insert into classedstopwords values (5, 'لعل', 'لَعَلَّ', 'حرف', 'إن و أخواتها', 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 'ناصب', 'اسم', '');
insert into classedstopwords values (6, 'لكن', 'لَكِنَّ', 'حرف', 'إن و أخواتها', 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 'ناصب', 'اسم', '');
insert into classedstopwords values (7, 'ليت', 'لَيْتَ', 'حرف', 'إن و أخواتها', 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 'ناصب', 'اسم', '');
insert into classedstopwords values (8, 'ثنا', 'ثَنَا', 'فعل', 'اختصار', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (9, 'بيد', 'بَيْدَ', 'اسم', 'استثناء', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (10, 'سوى', 'سِوَى', 'اسم', 'استثناء', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (11, 'غير', 'غَيْرَ', 'اسم', 'استثناء', 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 'جار', 'اسم', '');
insert into classedstopwords values (12, 'لاسيما', 'لاسِيَّمَا', 'حرف', 'استثناء', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (13, 'أولئك', 'أُولَئِكَ', 'اسم', 'اسم إشارة', 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (14, 'أولئكم', 'أُولَئِكُمْ', 'اسم', 'اسم إشارة', 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (15, 'أولاء', 'أُولَاءِ', 'اسم', 'اسم إشارة', 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (16, 'أولالك', 'أُولَالِكَ', 'اسم', 'اسم إشارة', 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (17, 'تان', 'تَانِ', 'اسم', 'اسم إشارة', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (18, 'تانك', 'تَانِكَ', 'اسم', 'اسم إشارة', 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (19, 'تلك', 'تِلْكَ', 'اسم', 'اسم إشارة', 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (20, 'تلكم', 'تِلْكُمْ', 'اسم', 'اسم إشارة', 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (21, 'تلكما', 'تِلْكُمَا', 'اسم', 'اسم إشارة', 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (22, 'ته', 'تِهِ', 'اسم', 'اسم إشارة', 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (23, 'تي', 'تِي', 'اسم', 'اسم إشارة', 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (24, 'تين', 'تَيْنِ', 'اسم', 'اسم إشارة', 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (25, 'تينك', 'تَيْنِكَ', 'اسم', 'اسم إشارة', 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (26, 'ثم', 'ثَمَّ', 'اسم', 'اسم إشارة', 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (27, 'ثمة', 'ثَمَّةَ', 'اسم', 'اسم إشارة', 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (28, 'ذا', 'ذَا', 'اسم', 'اسم إشارة', 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (29, 'ذاك', 'ذَاكَ', 'اسم', 'اسم إشارة', 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (30, 'ذان', 'ذَانِ', 'اسم', 'اسم إشارة', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (31, 'ذانك', 'ذَانِكَ', 'اسم', 'اسم إشارة', 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (32, 'ذلك', 'ذَلِكَ', 'اسم', 'اسم إشارة', 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (33, 'ذلكم', 'ذَلِكُمْ', 'اسم', 'اسم إشارة', 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (34, 'ذلكما', 'ذَلَكُمَا', 'اسم', 'اسم إشارة', 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (35, 'ذلكن', 'ذَلِكُنَّ', 'اسم', 'اسم إشارة', 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (36, 'ذه', 'ذِهِ', 'اسم', 'اسم إشارة', 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (37, 'ذوا', 'ذَوَا', 'اسم', 'اسم إشارة', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (38, 'ذواتا', 'ذَوَاتَا', 'اسم', 'اسم إشارة', 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (39, 'ذواتي', 'ذَوَاتَيْ', 'اسم', 'اسم إشارة', 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (40, 'ذوو', 'ذَوُو', 'اسم', 'اسم إشارة', 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 'جار', '', '');
insert into classedstopwords values (41, 'ذوي', 'ذَوِي', 'اسم', 'اسم إشارة', 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 'جار', '', '');
insert into classedstopwords values (42, 'ذي', 'ذِي', 'اسم', 'اسم إشارة', 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (43, 'ذين', 'ذَيْنِ', 'اسم', 'اسم إشارة', 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (44, 'ذينك', 'ذَيْنِكَ', 'اسم', 'اسم إشارة', 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (45, 'كذلك', 'كَذَلِكَ', 'اسم', 'اسم إشارة', 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (46, 'هؤلاء', 'هَؤُلَاءِ', 'اسم', 'اسم إشارة', 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (47, 'هاتان', 'هَاتَانِ', 'اسم', 'اسم إشارة', 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (48, 'هاته', 'هَاتِهِ', 'اسم', 'اسم إشارة', 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (49, 'هاتي', 'هَاتِي', 'اسم', 'اسم إشارة', 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (50, 'هاتين', 'هَاتَيْنِ', 'اسم', 'اسم إشارة', 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (51, 'هاهنا', 'هَاهُنَا', 'اسم', 'اسم إشارة', 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (52, 'هذا', 'هَذَا', 'اسم', 'اسم إشارة', 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (53, 'هذان', 'هَذَانِ', 'اسم', 'اسم إشارة', 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (54, 'هذه', 'هَذِهِ', 'اسم', 'اسم إشارة', 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (55, 'هذي', 'هَذِي', 'اسم', 'اسم إشارة', 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (56, 'هذين', 'هَذَيْنِ', 'اسم', 'اسم إشارة', 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (57, 'هكذا', 'هَكَذَا', 'اسم', 'اسم إشارة', 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (58, 'هنا', 'هُنَا', 'اسم', 'اسم إشارة', 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (59, 'هناك', 'هُنَاكَ', 'اسم', 'اسم إشارة', 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (60, 'هنالك', 'هُنَالِكَ', 'اسم', 'اسم إشارة', 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (61, 'أي', 'أَيُّ', 'اسم', 'اسم إضافة', 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 'جار', 'اسم', '');
insert into classedstopwords values (62, 'إذ', 'إِذْ', 'اسم', 'اسم إضافة', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'جار', 'اسم', '');
insert into classedstopwords values (63, 'إذا', 'إِذَا', 'اسم', 'اسم إضافة', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'جار', 'اسم', '');
insert into classedstopwords values (64, 'ابن', 'اِبْنُ', 'اسم', 'اسم إضافة', 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 'جار', 'اسم', '');
insert into classedstopwords values (65, 'بعض', 'بَعْضُ', 'اسم', 'اسم إضافة', 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 'جار', 'اسم', '');
insert into classedstopwords values (66, 'تجاه', 'تُجَاهَ', 'اسم', 'اسم إضافة', 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 'جار', 'اسم', '');
insert into classedstopwords values (67, 'تلقاء', 'تِلْقَاءَ', 'اسم', 'اسم إضافة', 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 'جار', 'اسم', '');
insert into classedstopwords values (68, 'جميع', 'جَمِيعَ', 'اسم', 'اسم إضافة', 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 'جار', 'اسم', '');
insert into classedstopwords values (69, 'حسب', 'حَسْبُ', 'اسم', 'اسم إضافة', 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 'جار', 'اسم', '');
insert into classedstopwords values (70, 'حيث', 'حَيْثُ', 'اسم', 'اسم إضافة', 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'جار', 'اسم', '');
insert into classedstopwords values (71, 'سبحان', 'سُبْحَانَ', 'اسم', 'اسم إضافة', 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 'جار', 'اسم', '');
insert into classedstopwords values (72, 'سوى', 'سِوَى', 'اسم', 'اسم إضافة', 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 'جار', 'اسم', '');
insert into classedstopwords values (73, 'شبه', 'شِبْهُ', 'اسم', 'اسم إضافة', 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 'جار', 'اسم', '');
insert into classedstopwords values (74, 'شطر', 'شَطْرَ', 'اسم', 'اسم إضافة', 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 'جار', 'اسم', '');
insert into classedstopwords values (75, 'كل', 'كُلُّ', 'اسم', 'اسم إضافة', 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 'جار', 'اسم', '');
insert into classedstopwords values (76, 'لعمر', 'لَعَمْرُ', 'اسم', 'اسم إضافة', 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 'جار', 'اسم', '');
insert into classedstopwords values (77, 'لما', 'لَمَّا', 'اسم', 'اسم إضافة', 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 'جار', 'اسم', '');
insert into classedstopwords values (78, 'مثل', 'مِثْلُ', 'اسم', 'اسم إضافة', 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 'جار', 'اسم', '');
insert into classedstopwords values (79, 'مع', 'مَعَ', 'اسم', 'اسم إضافة', 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 'جار', 'اسم', '');
insert into classedstopwords values (80, 'معاذ', 'مَعَاذَ', 'اسم', 'اسم إضافة', 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 'جار', 'اسم', '');
insert into classedstopwords values (81, 'نحو', 'نَحْوَ', 'اسم', 'اسم إضافة', 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 'جار', 'اسم', '');
insert into classedstopwords values (82, 'متى', 'مَتَى', 'اسم', 'اسم استفهام/ظرف زمان', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (83, 'أنى', 'أَنَّى', 'اسم', 'اسم الاستفهام', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (84, 'أي', 'أَيُّ', 'اسم', 'اسم الاستفهام', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (85, 'أيان', 'أَيَّانَ', 'اسم', 'اسم الاستفهام', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (86, 'أين', 'أَيْنَ', 'اسم', 'اسم الاستفهام', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (87, 'بكم', 'بِكَمْ', 'اسم', 'اسم الاستفهام', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (88, 'بما', 'بِمَا', 'اسم', 'اسم الاستفهام', 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (89, 'بماذا', 'بِمَاذَا', 'اسم', 'اسم الاستفهام', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (90, 'بمن', 'بِمَنْ', 'اسم', 'اسم الاستفهام', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (91, 'كم', 'كَمْ', 'اسم', 'اسم الاستفهام', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (92, 'كيف', 'كَيْفَ', 'اسم', 'اسم الاستفهام', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (93, 'ما', 'مَا', 'اسم', 'اسم الاستفهام', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (94, 'ماذا', 'مَاذَا', 'اسم', 'اسم الاستفهام', 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (95, 'متى', 'مَتَى', 'اسم', 'اسم الاستفهام', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (96, 'مما', 'مِمَّا', 'اسم', 'اسم الاستفهام', 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (97, 'ممن', 'مِمَّنْ', 'اسم', 'اسم الاستفهام', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (98, 'من', 'مَنْ', 'اسم', 'اسم الاستفهام', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (99, 'أنى', 'أَنَّى', 'اسم', 'اسم الشرط', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (100, 'أي', 'أَيُّ', 'اسم', 'اسم الشرط', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (101, 'أيان', 'أَيَّانَ', 'اسم', 'اسم الشرط', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (102, 'أين', 'أَيْنَ', 'اسم', 'اسم الشرط', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (103, 'أينما', 'أَيْنَمَا', 'اسم', 'اسم الشرط', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (104, 'حيثما', 'حَيْثُمَا', 'اسم', 'اسم الشرط', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (105, 'كيفما', 'كَيْفَمَا', 'اسم', 'اسم الشرط', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (106, 'ما', 'مَا', 'اسم', 'اسم الشرط', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (107, 'متى', 'مَتَى', 'اسم', 'اسم الشرط', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (108, 'من', 'مَنْ', 'اسم', 'اسم الشرط', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (109, 'مهما', 'مَهْمَا', 'اسم', 'اسم الشرط', 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (110, 'أقل', 'أَقَلُّ', 'اسم', 'اسم تفضيل', 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, '', '', '');
insert into classedstopwords values (111, 'أكثر', 'أَكْثَرُ', 'اسم', 'اسم تفضيل', 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, '', '', '');
insert into classedstopwords values (112, 'إذا', 'إذاً', 'حرف', 'اسم شرط', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (113, 'آها', 'آهاً', 'اسم فعل', 'اسم صوت', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (114, 'بس', 'بَسّْ', 'اسم فعل', 'اسم صوت', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (115, 'حاي', 'حَايْ', 'اسم فعل', 'اسم صوت', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (116, 'صه', 'صَهْ', 'اسم فعل', 'اسم صوت', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (117, 'صه', 'صَهٍ', 'اسم فعل', 'اسم صوت', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (118, 'طاق', 'طَاقْ', 'اسم فعل', 'اسم صوت', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (119, 'طق', 'طَقْ', 'اسم فعل', 'اسم صوت', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (120, 'عدس', 'عَدَسْ', 'اسم فعل', 'اسم صوت', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (121, 'كخ', 'كِخْ', 'اسم فعل', 'اسم صوت', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (122, 'نخ', 'نَخْ', 'اسم فعل', 'اسم صوت', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (123, 'هج', 'هَجْ', 'اسم فعل', 'اسم صوت', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (124, 'وا', 'وَا', 'اسم فعل', 'اسم صوت', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (125, 'واها', 'وَاهاً', 'اسم فعل', 'اسم صوت', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (126, 'وي', 'وَيْ', 'اسم فعل', 'اسم صوت', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (127, 'آمين', 'آمِينَ', 'اسم فعل', 'اسم فعل', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (128, 'آه', 'آهٍ', 'اسم فعل', 'اسم فعل', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (129, 'أف', 'أُفٍّ', 'اسم فعل', 'اسم فعل', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (130, 'أف', 'أُفٍّ', 'اسم فعل', 'اسم فعل', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (131, 'أمامك', 'أَمَامَكَ', 'اسم فعل', 'اسم فعل', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (132, 'أوه', 'أَوَّهْ', 'اسم فعل', 'اسم فعل', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (133, 'إليك', 'إِلَيْكَ', 'اسم فعل', 'اسم فعل', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (134, 'إليكم', 'إِلَيْكُمْ', 'اسم فعل', 'اسم فعل', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (135, 'إليكما', 'إِلَيْكُمَا', 'اسم فعل', 'اسم فعل', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (136, 'إليكن', 'إِلَيْكُنَّ', 'اسم فعل', 'اسم فعل', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (137, 'إيه', 'إيهِ', 'اسم فعل', 'اسم فعل', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (138, 'بخ', 'بخٍ', 'اسم فعل', 'اسم فعل', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (139, 'بس', 'بَسْ', 'اسم فعل', 'اسم فعل', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (140, 'بطآن', 'بُطْآنَ', 'اسم فعل', 'اسم فعل', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (141, 'بله', 'بَلْهَ', 'اسم فعل', 'اسم فعل', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (142, 'حذار', 'حَذَارِ', 'اسم فعل', 'اسم فعل', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (143, 'حي', 'حَيَّ', 'اسم فعل', 'اسم فعل', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (144, 'دونك', 'دُونَكَ', 'اسم فعل', 'اسم فعل', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (145, 'رويدك', 'رُوَيْدَكَ', 'اسم فعل', 'اسم فعل', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (146, 'سرعان', 'سُرْعَانَ', 'اسم فعل', 'اسم فعل', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (147, 'شتان', 'شَتَّانَ', 'اسم فعل', 'اسم فعل', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (148, 'عليك', 'عَلَيْكَ', 'اسم فعل', 'اسم فعل', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (149, 'مكانك', 'مَكَانَكَ', 'اسم فعل', 'اسم فعل', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (150, 'مكانك', 'مَكَانَكِ', 'اسم فعل', 'اسم فعل', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (151, 'مكانكم', 'مَكَانَكُمْ', 'اسم فعل', 'اسم فعل', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (152, 'مكانكما', 'مَكَانَكُمَا', 'اسم فعل', 'اسم فعل', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (153, 'مكانكن', 'مَكَانَكُنَّ', 'اسم فعل', 'اسم فعل', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (154, 'مه', 'مَهْ', 'اسم فعل', 'اسم فعل', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (155, 'ها', 'هَا', 'اسم فعل', 'اسم فعل', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (156, 'هاؤم', 'هَاؤُمُ', 'اسم فعل', 'اسم فعل', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (157, 'هاك', 'هَاكَ', 'اسم فعل', 'اسم فعل', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (158, 'هلم', 'هَلُمَّ', 'اسم فعل', 'اسم فعل', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (159, 'هيا', 'هَيَّا', 'اسم فعل', 'اسم فعل', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (160, 'هيت', 'هِيتَ', 'اسم فعل', 'اسم فعل', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (161, 'هيهات', 'هَيْهَاتَ', 'اسم فعل', 'اسم فعل', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (162, 'وا', 'وَا', 'اسم فعل', 'اسم فعل', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (163, 'وراءك', 'وَرَاءَكَ', 'اسم فعل', 'اسم فعل', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (164, 'وشكان', 'وُشْكَانَ', 'اسم فعل', 'اسم فعل', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (165, 'ويكأن', 'وَيْكَأَنَّ', 'اسم فعل', 'اسم فعل', 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (166, 'أي', 'أَيُّ', 'اسم', 'اسم موصول', 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, '', '', '');
insert into classedstopwords values (167, 'الألاء', 'الْأَلَاءُ', 'اسم', 'اسم موصول', 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, '', '', '');
insert into classedstopwords values (168, 'الألى', 'الْأُلَى', 'اسم', 'اسم موصول', 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, '', '', '');
insert into classedstopwords values (169, 'التي', 'الَّتِي', 'اسم', 'اسم موصول', 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, '', '', '');
insert into classedstopwords values (170, 'الذي', 'الَّذِي', 'اسم', 'اسم موصول', 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, '', '', '');
insert into classedstopwords values (171, 'الذين', 'الَّذِينَ', 'اسم', 'اسم موصول', 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, '', '', '');
insert into classedstopwords values (172, 'اللائي', 'الْلَائِي', 'اسم', 'اسم موصول', 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, '', '', '');
insert into classedstopwords values (173, 'اللاتي', 'الْلَاتِي', 'اسم', 'اسم موصول', 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, '', '', '');
insert into classedstopwords values (174, 'اللتان', 'الْلَتَانِ', 'اسم', 'اسم موصول', 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, '', '', '');
insert into classedstopwords values (175, 'اللتيا', 'الْلَتَيَّا', 'اسم', 'اسم موصول', 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, '', '', '');
insert into classedstopwords values (176, 'اللتين', 'الْلَتَيْنِ', 'اسم', 'اسم موصول', 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, '', '', '');
insert into classedstopwords values (177, 'اللذان', 'الْلَذَانِ', 'اسم', 'اسم موصول', 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, '', '', '');
insert into classedstopwords values (178, 'اللذين', 'الْلَذَيْنِ', 'اسم', 'اسم موصول', 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, '', '', '');
insert into classedstopwords values (179, 'اللواتي', 'الْلَوَاتِي', 'اسم', 'اسم موصول', 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, '', '', '');
insert into classedstopwords values (180, 'ذا', 'ذَا', 'اسم', 'اسم موصول', 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (181, 'ذات', 'ذَاتُ', 'اسم', 'اسم موصول', 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 'جار', '', '');
insert into classedstopwords values (182, 'ما', 'مَا', 'اسم', 'اسم موصول', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (183, 'من', 'مَنْ', 'اسم', 'اسم موصول', 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (184, 'أب', 'أَبُ', 'اسم', 'الأسماء الخمسة', 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, '', '', '');
insert into classedstopwords values (185, 'أبا', 'أَبَا', 'اسم', 'الأسماء الخمسة', 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 'جار', 'اسم', '');
insert into classedstopwords values (186, 'أبو', 'أَبُو', 'اسم', 'الأسماء الخمسة', 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 'جار', 'اسم', '');
insert into classedstopwords values (187, 'أبي', 'أَبِي', 'اسم', 'الأسماء الخمسة', 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 'جار', 'اسم', '');
insert into classedstopwords values (188, 'أخ', 'أَخُ', 'اسم', 'الأسماء الخمسة', 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, '', '', '');
insert into classedstopwords values (189, 'أخا', 'أَخَا', 'اسم', 'الأسماء الخمسة', 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 'جار', 'اسم', '');
insert into classedstopwords values (190, 'أخو', 'أَخُو', 'اسم', 'الأسماء الخمسة', 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 'جار', 'اسم', '');
insert into classedstopwords values (191, 'أخي', 'أَخِي', 'اسم', 'الأسماء الخمسة', 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 'جار', 'اسم', '');
insert into classedstopwords values (192, 'حم', 'حَمُ', 'اسم', 'الأسماء الخمسة', 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, '', '', '');
insert into classedstopwords values (193, 'حما', 'حَمَا', 'اسم', 'الأسماء الخمسة', 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 'جار', 'اسم', '');
insert into classedstopwords values (194, 'حمو', 'حَمُو', 'اسم', 'الأسماء الخمسة', 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 'جار', 'اسم', '');
insert into classedstopwords values (195, 'حمي', 'حَمِي', 'اسم', 'الأسماء الخمسة', 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 'جار', 'اسم', '');
insert into classedstopwords values (196, 'ذا', 'ذَا', 'اسم', 'الأسماء الخمسة', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'جار', 'اسم', '');
insert into classedstopwords values (197, 'ذو', 'ذُو', 'اسم', 'الأسماء الخمسة', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'جار', 'اسم', '');
insert into classedstopwords values (198, 'ذي', 'ذِي', 'اسم', 'الأسماء الخمسة', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'جار', 'اسم', '');
insert into classedstopwords values (199, 'فا', 'فَا', 'اسم', 'الأسماء الخمسة', 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 'جار', 'اسم', '');
insert into classedstopwords values (200, 'فو', 'فُو', 'اسم', 'الأسماء الخمسة', 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 'جار', 'اسم', '');
insert into classedstopwords values (201, 'في', 'فِي', 'اسم', 'الأسماء الخمسة', 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 'جار', 'اسم', '');
insert into classedstopwords values (202, 'لن', 'لَنْ', 'حرف', 'الحروف(حروف)', 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (203, 'لو', 'لَوْ', 'حرف', 'الحروف(حروف)', 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (204, 'لولا', 'لَوْلَا', 'حرف', 'الحروف(حروف)', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (205, 'لوما', 'لَوْمَا', 'حرف', 'الحروف(حروف)', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (206, 'نعم', 'نَعَمْ', 'حرف', 'الحروف(حروف)', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (207, 'بئس', 'بِئْسَ', 'فعل', 'المدح والذم', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'رافع', 'اسم', '');
insert into classedstopwords values (208, 'حبذا', 'حَبَّذَا', 'فعل', 'المدح والذم', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'رافع', 'اسم', '');
insert into classedstopwords values (209, 'ساء', 'سَاءَ', 'فعل', 'المدح والذم', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'رافع', 'اسم', '');
insert into classedstopwords values (210, 'ساءما', 'سَاءَمَا', 'فعل', 'المدح والذم', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'رافع', 'اسم', '');
insert into classedstopwords values (211, 'نعم', 'نِعْمَ', 'فعل', 'المدح والذم', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'رافع', 'اسم', '');
insert into classedstopwords values (212, 'نعما', 'نِعِمّا', 'فعل', 'المدح والذم', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'رافع', 'اسم', '');
insert into classedstopwords values (213, 'إن', 'إِنْ', 'حرف', 'المشبهة بليس', 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'رافع', 'اسم', '');
insert into classedstopwords values (214, 'لا', 'لَا', 'حرف', 'المشبهة بليس', 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 'رافع', 'اسم', '');
insert into classedstopwords values (215, 'لات', 'لَاتَ', 'حرف', 'المشبهة بليس', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'رافع', 'اسم', '');
insert into classedstopwords values (216, 'ما', 'مَا', 'حرف', 'المشبهة بليس', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'رافع', 'اسم', '');
insert into classedstopwords values (217, 'أي', 'أي', 'حرف', 'تعليل', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (218, 'حتى', 'حَتَّى', 'حرف', 'تعليل', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (219, 'كي', 'كَيْ', 'حرف', 'تعليل', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'ناصب', 'فعل', '');
insert into classedstopwords values (220, 'أجمع', 'أَجْمَعَ', 'اسم', 'توكيد', 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, '', '', '');
insert into classedstopwords values (221, 'جميع', 'جَمِيعَ', 'اسم', 'توكيد', 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, '', '', '');
insert into classedstopwords values (222, 'عامة', 'عَامَّةَ', 'اسم', 'توكيد', 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, '', '', '');
insert into classedstopwords values (223, 'عين', 'عَيْنَ', 'اسم', 'توكيد', 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, '', '', '');
insert into classedstopwords values (224, 'كل', 'كُلَّ', 'اسم', 'توكيد', 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, '', '', '');
insert into classedstopwords values (225, 'كلا', 'كِلَا', 'حرف', 'توكيد', 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (226, 'كلاهما', 'كِلَاهُمَا', 'حرف', 'توكيد', 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (227, 'كلتا', 'كِلْتَا', 'اسم', 'توكيد', 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, '', '', '');
insert into classedstopwords values (228, 'كليكما', 'كِلَيْكُمَا', 'حرف', 'توكيد', 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (229, 'كليهما', 'كِلَيْهِمَا', 'حرف', 'توكيد', 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (230, 'نفس', 'نَفْسُ', 'اسم', 'توكيد', 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, '', '', '');
insert into classedstopwords values (231, 'ء', 'ء', 'حرف ابجدي', 'حرف ابجدي', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (232, 'آ', 'آ', 'حرف ابجدي', 'حرف ابجدي', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (233, 'أ', 'أ', 'حرف ابجدي', 'حرف ابجدي', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (234, 'أ', 'أ', 'حرف ابجدي', 'حرف ابجدي', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (235, 'ؤ', 'ؤ', 'حرف ابجدي', 'حرف ابجدي', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (236, 'ئ', 'ئ', 'حرف ابجدي', 'حرف ابجدي', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (237, 'ب', 'ب', 'حرف ابجدي', 'حرف ابجدي', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (238, 'ة', 'ة', 'حرف ابجدي', 'حرف ابجدي', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (239, 'ت', 'ت', 'حرف ابجدي', 'حرف ابجدي', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (240, 'ث', 'ث', 'حرف ابجدي', 'حرف ابجدي', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (241, 'ج', 'ج', 'حرف ابجدي', 'حرف ابجدي', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (242, 'ح', 'ح', 'حرف ابجدي', 'حرف ابجدي', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (243, 'خ', 'خ', 'حرف ابجدي', 'حرف ابجدي', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (244, 'د', 'د', 'حرف ابجدي', 'حرف ابجدي', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (245, 'ذ', 'ذ', 'حرف ابجدي', 'حرف ابجدي', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (246, 'ر', 'ر', 'حرف ابجدي', 'حرف ابجدي', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (247, 'ز', 'ز', 'حرف ابجدي', 'حرف ابجدي', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (248, 'س', 'س', 'حرف ابجدي', 'حرف ابجدي', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (249, 'ش', 'ش', 'حرف ابجدي', 'حرف ابجدي', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (250, 'ص', 'ص', 'حرف ابجدي', 'حرف ابجدي', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (251, 'ض', 'ض', 'حرف ابجدي', 'حرف ابجدي', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (252, 'ط', 'ط', 'حرف ابجدي', 'حرف ابجدي', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (253, 'ظ', 'ظ', 'حرف ابجدي', 'حرف ابجدي', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (254, 'ع', 'ع', 'حرف ابجدي', 'حرف ابجدي', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (255, 'غ', 'غ', 'حرف ابجدي', 'حرف ابجدي', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (256, 'ف', 'ف', 'حرف ابجدي', 'حرف ابجدي', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (257, 'ق', 'ق', 'حرف ابجدي', 'حرف ابجدي', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (258, 'ك', 'ك', 'حرف ابجدي', 'حرف ابجدي', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (259, 'ل', 'ل', 'حرف ابجدي', 'حرف ابجدي', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (260, 'م', 'م', 'حرف ابجدي', 'حرف ابجدي', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (261, 'ن', 'ن', 'حرف ابجدي', 'حرف ابجدي', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (262, 'ه', 'ه', 'حرف ابجدي', 'حرف ابجدي', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (263, 'و', 'و', 'حرف ابجدي', 'حرف ابجدي', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (264, 'ى', 'ى', 'حرف ابجدي', 'حرف ابجدي', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (265, 'ي', 'ي', 'حرف ابجدي', 'حرف ابجدي', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (266, 'إلا', 'إلّا', 'حرف', 'حرف استثناء', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'رافع', 'اسم', '');
insert into classedstopwords values (267, 'حاشا', 'حَاشَا', 'فعل', 'حرف استثناء', 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 'جار', 'اسم', '');
insert into classedstopwords values (268, 'خلا', 'خَلَا', 'فعل', 'حرف استثناء', 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 'جار', 'اسم', '');
insert into classedstopwords values (269, 'عدا', 'عَدَا', 'فعل', 'حرف استثناء', 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 'جار', 'اسم', '');
insert into classedstopwords values (270, 'لكن', 'لَكِنْ', 'حرف', 'حرف استدراك', 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (271, 'فيم', 'فِيمَ', 'حرف', 'حرف استفهام', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'رافع', 'اسم', '');
insert into classedstopwords values (272, 'فيما', 'فِيمَا', 'حرف', 'حرف استفهام', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'رافع', 'اسم', '');
insert into classedstopwords values (273, 'هل', 'هَلْ', 'حرف', 'حرف استفهام', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'رافع', 'اسم', '');
insert into classedstopwords values (274, 'سوف', 'سَوْفَ', 'حرف', 'حرف استقبال', 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 'رافع', 'فعل', '');
insert into classedstopwords values (275, 'هلا', 'هَلّا', 'حرف', 'حرف تحضيض', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (276, 'قد', 'قَدْ', 'حرف', 'حرف تحقيق/ توقع', 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 'عاطل', 'فعل', '');
insert into classedstopwords values (277, 'إما', 'إِمَّا', 'حرف', 'حرف تخيير وتفصيل', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (278, 'كأنما', 'كَأَنَّمَا', 'حرف', 'حرف تشبيه', 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, '', '', '');
insert into classedstopwords values (279, 'كما', 'كَمَا', 'حرف', 'حرف تشبيه', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (280, 'لكي', 'لِكَيْ', 'حرف', 'حرف تعليل', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'ناصب', 'فعل', '');
insert into classedstopwords values (281, 'لكيلا', 'لِكَيْلَا', 'حرف', 'حرف تعليل', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'ناصب', 'فعل', '');
insert into classedstopwords values (282, 'إلى', 'إِلَى', 'حرف', 'حرف جر', 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 'جار', 'اسم', '');
insert into classedstopwords values (283, 'بلا', 'بِلَا', 'حرف', 'حرف جر', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'جار', 'اسم', '');
insert into classedstopwords values (284, 'حتى', 'حَتَّى', 'حرف', 'حرف جر', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'جار', 'اسم', '');
insert into classedstopwords values (285, 'رب', 'رُبَّ', 'حرف', 'حرف جر', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'جار', 'اسم', '');
insert into classedstopwords values (286, 'على', 'عَلَى', 'حرف', 'حرف جر', 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 'جار', 'اسم', '');
insert into classedstopwords values (287, 'عن', 'عَنْ', 'حرف', 'حرف جر', 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 'جار', 'اسم', '');
insert into classedstopwords values (288, 'في', 'فِي', 'حرف', 'حرف جر', 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 'جار', 'اسم', '');
insert into classedstopwords values (289, 'مذ', 'مُذْ', 'حرف', 'حرف جر', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'جار', 'اسم', '');
insert into classedstopwords values (290, 'من', 'مِنْ', 'حرف', 'حرف جر', 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 'جار', 'اسم', '');
insert into classedstopwords values (291, 'منذ', 'مُنْذُ', 'حرف', 'حرف جر', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'جار', 'اسم', '');
insert into classedstopwords values (292, 'عما', 'عَمَّا', 'حرف', 'حرف جر مكفوف', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'عاطل', '', '');
insert into classedstopwords values (293, 'إن', 'إِنْ', 'حرف', 'حرف جزم', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'جازم', 'فعل', '');
insert into classedstopwords values (294, 'لم', 'لَمْ', 'حرف', 'حرف جزم', 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 'جازم', 'فعل', '');
insert into classedstopwords values (295, 'لما', 'لَمَّا', 'حرف', 'حرف جزم', 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 'جازم', 'فعل', '');
insert into classedstopwords values (296, 'أجل', 'أَجَلْ', 'حرف', 'حرف جواب', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (297, 'إذن', 'إِذَنْ', 'حرف', 'حرف جواب', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (298, 'إي', 'إِي', 'حرف', 'حرف جواب', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (299, 'بلى', 'بَلَى', 'حرف', 'حرف جواب', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (300, 'جلل', 'جَلَلْ', 'حرف', 'حرف جواب', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (301, 'جير', 'جَيْرِ', 'حرف', 'حرف جواب', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (302, 'كلا', 'كَلَّا', 'حرف', 'حرف ردع', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (303, 'إذما', 'إَذْمَا', 'حرف', 'حرف شرط', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (304, 'إن', 'إِنْ', 'حرف', 'حرف شرط', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (305, 'لئن', 'لَئِنْ', 'حرف', 'حرف شرط', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (306, 'أما', 'أَمَّا', 'حرف', 'حرف شرط وتفصيل وتوكيد', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (307, 'ألا', 'أَلَا', 'حرف', 'حرف عرض', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (308, 'أما', 'أَمَا', 'حرف', 'حرف عرض', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (309, 'أم', 'أَمْ', 'حرف', 'حرف عطف منفصل', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'متبع', 'فعل:اسم', '');
insert into classedstopwords values (310, 'أو', 'أَوْ', 'حرف', 'حرف عطف منفصل', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'متبع', '', '');
insert into classedstopwords values (311, 'بل', 'بَلْ', 'حرف', 'حرف عطف منفصل', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'متبع', '', '');
insert into classedstopwords values (312, 'ثم', 'ثُمَّ', 'حرف', 'حرف عطف منفصل', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'متبع', '', '');
insert into classedstopwords values (313, 'و', 'وَ', 'حرف', 'حرف عطف منفصل', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'متبع', 'اسم فعل', '');
insert into classedstopwords values (314, 'أيا', 'أَيَا', 'حرف', 'حرف نداء', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (315, 'هيا', 'هَيَا', 'حرف', 'حرف نداء', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (316, 'أن', 'أَنْ', 'حرف', 'حرف نصب', 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 'ناصب', 'فعل', '');
insert into classedstopwords values (317, 'لئلا', 'لِئَلَّا', 'حرف', 'حرف نصب', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'ناصب', 'فعل', '');
insert into classedstopwords values (318, 'بك', 'بِكَ', 'ضمير', 'ضمير متصل مجرور', 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (319, 'بكم', 'بِكُمْ', 'ضمير', 'ضمير متصل مجرور', 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (320, 'بكما', 'بِكُمَا', 'ضمير', 'ضمير متصل مجرور', 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (321, 'بكن', 'بِكُنَّ', 'ضمير', 'ضمير متصل مجرور', 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (322, 'بنا', 'بِنَا', 'ضمير', 'ضمير متصل مجرور', 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (323, 'به', 'بِهِ', 'ضمير', 'ضمير متصل مجرور', 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (324, 'بها', 'بِهَا', 'ضمير', 'ضمير متصل مجرور', 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (325, 'بي', 'بِي', 'ضمير', 'ضمير متصل مجرور', 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (326, 'لك', 'لَكَ', 'ضمير', 'ضمير متصل مجرور', 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (327, 'لكم', 'لَكُمْ', 'ضمير', 'ضمير متصل مجرور', 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (328, 'لكما', 'لَكُمَا', 'ضمير', 'ضمير متصل مجرور', 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (329, 'لكن', 'لَكُنَّ', 'ضمير', 'ضمير متصل مجرور', 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (330, 'لنا', 'لَنَا', 'ضمير', 'ضمير متصل مجرور', 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (331, 'له', 'لَهُ', 'ضمير', 'ضمير متصل مجرور', 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (332, 'لها', 'لَهَا', 'ضمير', 'ضمير متصل مجرور', 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (333, 'لي', 'لِي', 'ضمير', 'ضمير متصل مجرور', 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (334, 'أنا', 'أَنَا', 'ضمير', 'ضمير منفصل', 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, '', '', '');
insert into classedstopwords values (335, 'أنت', 'أَنْتَ', 'ضمير', 'ضمير منفصل', 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, '', '', '');
insert into classedstopwords values (336, 'أنت', 'أَنْتِ', 'ضمير', 'ضمير منفصل', 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, '', '', '');
insert into classedstopwords values (337, 'أنتم', 'أَنْتُمْ', 'ضمير', 'ضمير منفصل', 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, '', '', '');
insert into classedstopwords values (338, 'أنتما', 'أَنْتُمَا', 'ضمير', 'ضمير منفصل', 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, '', '', '');
insert into classedstopwords values (339, 'أنتن', 'أَنْتُنَّ', 'ضمير', 'ضمير منفصل', 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, '', '', '');
insert into classedstopwords values (340, 'نحن', 'نَحْنُ', 'ضمير', 'ضمير منفصل', 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, '', '', '');
insert into classedstopwords values (341, 'هم', 'هُمْ', 'ضمير', 'ضمير منفصل', 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, '', '', '');
insert into classedstopwords values (342, 'هما', 'هُمَا', 'ضمير', 'ضمير منفصل', 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, '', '', '');
insert into classedstopwords values (343, 'هن', 'هُنَّ', 'ضمير', 'ضمير منفصل', 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, '', '', '');
insert into classedstopwords values (344, 'هو', 'هُوَ', 'ضمير', 'ضمير منفصل', 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, '', '', '');
insert into classedstopwords values (345, 'هي', 'هِي', 'ضمير', 'ضمير منفصل', 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, '', '', '');
insert into classedstopwords values (346, 'إياك', 'إِيَّاكَ', 'ضمير', 'ضمير منفصل منصوب', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (347, 'إياك', 'إِيَّاكِ', 'ضمير', 'ضمير منفصل منصوب', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (348, 'إياكم', 'إِيَّاكُمْ', 'ضمير', 'ضمير منفصل منصوب', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (349, 'إياكما', 'إِيَّاكُمَا', 'ضمير', 'ضمير منفصل منصوب', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (350, 'إياكن', 'إِيَّاكُنَّ', 'ضمير', 'ضمير منفصل منصوب', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (351, 'إيانا', 'إِيَّانَا', 'ضمير', 'ضمير منفصل منصوب', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (352, 'إياه', 'إِيَّاهُ', 'ضمير', 'ضمير منفصل منصوب', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (353, 'إياها', 'إِيَّاهَا', 'ضمير', 'ضمير منفصل منصوب', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (354, 'إياهم', 'إِيَّاهُمْ', 'ضمير', 'ضمير منفصل منصوب', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (355, 'إياهما', 'إِيَّاهُمَا', 'ضمير', 'ضمير منفصل منصوب', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (356, 'إياهن', 'إِيَّاهُنَّ', 'ضمير', 'ضمير منفصل منصوب', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (357, 'إياي', 'إِيَّايَ', 'ضمير', 'ضمير منفصل منصوب', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (358, 'بدون', 'بِدُونِ', 'اسم', 'ظرف', 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 'جار', 'اسم', '');
insert into classedstopwords values (359, 'دون', 'دُونَ', 'اسم', 'ظرف', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'جار', 'اسم', '');
insert into classedstopwords values (360, 'ريث', 'رَيْثَ', 'اسم', 'ظرف', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'جار', 'اسم', '');
insert into classedstopwords values (361, 'عند', 'عِنْدَ', 'اسم', 'ظرف', 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 'جار', 'اسم', '');
insert into classedstopwords values (362, 'عندما', 'عِنْدَمَا', 'اسم', 'ظرف', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (363, 'عوض', 'عِوَضَ', 'اسم', 'ظرف', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'جار', 'اسم', '');
insert into classedstopwords values (364, 'قبل', 'قَبْلَ', 'اسم', 'ظرف', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'جار', 'اسم', '');
insert into classedstopwords values (365, 'قط', 'قَطُّ', 'حرف', 'ظرف', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'جار', 'اسم', '');
insert into classedstopwords values (366, 'كلما', 'كُلَّمَا', 'اسم', 'ظرف', 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (367, 'لدن', 'لَدُنْ', 'اسم', 'ظرف', 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 'جار', 'اسم', '');
insert into classedstopwords values (368, 'لدى', 'لَدَى', 'اسم', 'ظرف', 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 'جار', 'اسم', '');
insert into classedstopwords values (369, 'لما', 'لَمَّا', 'حرف', 'ظرف', 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (370, 'آناء', 'آنَاءَ', 'اسم', 'ظرف زمان', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'جار', 'اسم', '');
insert into classedstopwords values (371, 'آنفا', 'آنِفًا', 'اسم', 'ظرف زمان', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'عاطل', '', '');
insert into classedstopwords values (372, 'أبدا', 'أَبَدًا', 'اسم', 'ظرف زمان', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'عاطل', '', '');
insert into classedstopwords values (373, 'أثناء', 'أَثْنَاءَ', 'اسم', 'ظرف زمان', 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 'جار', 'اسم', '');
insert into classedstopwords values (374, 'أصلا', 'أَصْلًا', 'اسم', 'ظرف زمان', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'عاطل', '', '');
insert into classedstopwords values (375, 'أمد', 'أَمَدَ', 'اسم', 'ظرف زمان', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'جار', 'اسم', '');
insert into classedstopwords values (376, 'أمس', 'أَمْسِ', 'اسم', 'ظرف زمان', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (377, 'أول', 'أَوَّلَ', 'اسم', 'ظرف زمان', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'جار', 'اسم', '');
insert into classedstopwords values (378, 'أيان', 'أَيَّانَ', 'اسم', 'ظرف زمان', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'جار', 'اسم', '');
insert into classedstopwords values (379, 'إذ', 'إِذْ', 'اسم', 'ظرف زمان', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'جار', 'اسم', '');
insert into classedstopwords values (380, 'الآن', 'الْآنَ', 'اسم', 'ظرف زمان', 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 'عاطل', '', '');
insert into classedstopwords values (381, 'بعد', 'بَعْدَ', 'اسم', 'ظرف زمان', 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 'جار', 'اسم', '');
insert into classedstopwords values (382, 'تارة', 'تَارَةً', 'اسم', 'ظرف زمان', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'عاطل', '', '');
insert into classedstopwords values (383, 'حين', 'حِينَ', 'اسم', 'ظرف زمان', 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 'جار', 'اسم', '');
insert into classedstopwords values (384, 'زمان', 'زَمَانَ', 'اسم', 'ظرف زمان', 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 'جار', 'اسم', '');
insert into classedstopwords values (385, 'ساعة', 'سَاعَةَ', 'اسم', 'ظرف زمان', 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 'جار', 'اسم', '');
insert into classedstopwords values (386, 'شهر', 'شَهْرَ', 'اسم', 'ظرف زمان', 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 'جار', 'اسم', '');
insert into classedstopwords values (387, 'صباح', 'صَبَاحَ', 'اسم', 'ظرف زمان', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'جار', 'اسم', '');
insert into classedstopwords values (388, 'ضحوة', 'ضَحْوَةً', 'اسم', 'ظرف زمان', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'عاطل', '', '');
insert into classedstopwords values (389, 'غدا', 'غَدًا', 'اسم', 'ظرف زمان', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'عاطل', '', '');
insert into classedstopwords values (390, 'غداة', 'غَدَاةَ', 'اسم', 'ظرف زمان', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'عاطل', '', '');
insert into classedstopwords values (391, 'غروب', 'غُرُوبَ', 'اسم', 'ظرف زمان', 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 'جار', 'اسم', '');
insert into classedstopwords values (392, 'لحظة', 'لَحْظَةَ', 'اسم', 'ظرف زمان', 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 'جار', 'اسم', '');
insert into classedstopwords values (393, 'ليل', 'لَيْلَ', 'اسم', 'ظرف زمان', 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 'جار', 'اسم', '');
insert into classedstopwords values (394, 'مذ', 'مُذْ', 'حرف', 'ظرف زمان', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (395, 'مرة', 'مَرَّةً', 'اسم', 'ظرف زمان', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'جار', 'اسم', '');
insert into classedstopwords values (396, 'مساء', 'مَسَاءَ', 'اسم', 'ظرف زمان', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'جار', 'اسم', '');
insert into classedstopwords values (397, 'منذ', 'مُنْذُ', 'حرف', 'ظرف زمان', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (398, 'وقت', 'وَقْتَ', 'اسم', 'ظرف زمان', 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 'جار', 'اسم', '');
insert into classedstopwords values (399, 'يومئذ', 'يَوْمَئِذٍ', 'اسم', 'ظرف زمان', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'عاطل', '', '');
insert into classedstopwords values (400, 'خلال', 'خِلَالَ', 'اسم', 'ظرف زمان/مكان', 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 'جار', 'اسم', '');
insert into classedstopwords values (401, 'أسفل', 'أَسْفَلَ', 'اسم', 'ظرف مكان', 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 'جار', 'اسم', '');
insert into classedstopwords values (402, 'أعلى', 'أَعْلَى', 'اسم', 'ظرف مكان', 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 'جار', 'اسم', '');
insert into classedstopwords values (403, 'أمام', 'أَمَامَ', 'اسم', 'ظرف مكان', 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 'جار', 'اسم', '');
insert into classedstopwords values (404, 'أين', 'أَيْنَ', 'اسم', 'ظرف مكان', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'جار', 'اسم', '');
insert into classedstopwords values (405, 'إزاء', 'إِزَاءَ', 'اسم', 'ظرف مكان', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'جار', 'اسم', '');
insert into classedstopwords values (406, 'بين', 'بَيْنَ', 'اسم', 'ظرف مكان', 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 'جار', 'اسم', '');
insert into classedstopwords values (407, 'تحت', 'تَحْتَ', 'اسم', 'ظرف مكان', 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 'جار', 'اسم', '');
insert into classedstopwords values (408, 'ثم', 'ثَمَّ', 'اسم', 'ظرف مكان', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'جار', 'اسم', '');
insert into classedstopwords values (409, 'جنب', 'جَنْبَ', 'اسم', 'ظرف مكان', 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 'جار', 'اسم', '');
insert into classedstopwords values (410, 'جنوب', 'جَنُوبَ', 'اسم', 'ظرف مكان', 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 'جار', 'اسم', '');
insert into classedstopwords values (411, 'حوالى', 'حَوَالَى', 'اسم', 'ظرف مكان', 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 'جار', 'اسم', '');
insert into classedstopwords values (412, 'حول', 'حَوْلَ', 'اسم', 'ظرف مكان', 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 'جار', 'اسم', '');
insert into classedstopwords values (413, 'خلف', 'خَلْفَ', 'اسم', 'ظرف مكان', 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 'جار', 'اسم', '');
insert into classedstopwords values (414, 'خلف', 'خَلْفَ', 'اسم', 'ظرف مكان', 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 'جار', 'اسم', '');
insert into classedstopwords values (415, 'شرق', 'شَرْقَ', 'اسم', 'ظرف مكان', 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 'جار', 'اسم', '');
insert into classedstopwords values (416, 'شمال', 'شَمَالَ', 'اسم', 'ظرف مكان', 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 'جار', 'اسم', '');
insert into classedstopwords values (417, 'ضمن', 'ضِمْنَ', 'اسم', 'ظرف مكان', 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 'جار', 'اسم', '');
insert into classedstopwords values (418, 'غرب', 'غَرْبَ', 'اسم', 'ظرف مكان', 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 'جار', 'اسم', '');
insert into classedstopwords values (419, 'فوق', 'فَوْقَ', 'اسم', 'ظرف مكان', 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 'جار', 'اسم', '');
insert into classedstopwords values (420, 'نحو', 'نَحوَ', 'اسم', 'ظرف مكان', 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 'جار', 'اسم', '');
insert into classedstopwords values (421, 'يمين', 'يَمِينَ', 'اسم', 'ظرف مكان', 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 'جار', 'اسم', '');
insert into classedstopwords values (422, 'طالما', 'طَالَمَا', 'فعل', 'فعل جامد', 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 'رافع', 'اسم', '');
insert into classedstopwords values (423, 'قلما', 'قَلَّمَا', 'فعل', 'فعل جامد', 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 'رافع', 'اسم', '');
insert into classedstopwords values (424, 'أخذ', 'أَخَذَ', 'فعل', 'كاد و اخواتها', 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 'رافع', 'اسم', '');
insert into classedstopwords values (425, 'أقبل', 'أَقْبَلَ', 'فعل', 'كاد و اخواتها', 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 'رافع', 'اسم', '');
insert into classedstopwords values (426, 'أنشأ', 'أَنْشَأَ', 'فعل', 'كاد و اخواتها', 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 'رافع', 'اسم', '');
insert into classedstopwords values (427, 'أوشك', 'أَوْشَكَ', 'فعل', 'كاد و اخواتها', 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 'رافع', 'اسم', '');
insert into classedstopwords values (428, 'ابتدأ', 'ابْتَدَأَ', 'فعل', 'كاد و اخواتها', 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 'رافع', 'اسم', '');
insert into classedstopwords values (429, 'اخلولق', 'اِخْلَوْلَقَ', 'فعل', 'كاد و اخواتها', 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 'رافع', 'اسم', '');
insert into classedstopwords values (430, 'انبرى', 'اِنْبَرَى', 'فعل', 'كاد و اخواتها', 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 'رافع', 'اسم', '');
insert into classedstopwords values (431, 'جعل', 'جَعَلَ', 'فعل', 'كاد و اخواتها', 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 'رافع', 'اسم', '');
insert into classedstopwords values (432, 'حرى', 'حَرَى', 'فعل', 'كاد و اخواتها', 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 'رافع', 'اسم', '');
insert into classedstopwords values (433, 'شرع', 'شَرَعَ', 'فعل', 'كاد و اخواتها', 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 'رافع', 'اسم', '');
insert into classedstopwords values (434, 'طفق', 'طَفِقَ', 'فعل', 'كاد و اخواتها', 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 'رافع', 'اسم', '');
insert into classedstopwords values (435, 'عسى', 'عَسَى', 'فعل', 'كاد و اخواتها', 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 'رافع', 'اسم', '');
insert into classedstopwords values (436, 'علق', 'عَلِقَ', 'فعل', 'كاد و اخواتها', 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 'رافع', 'اسم', '');
insert into classedstopwords values (437, 'قام', 'قَامَ', 'فعل', 'كاد و اخواتها', 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 'رافع', 'اسم', '');
insert into classedstopwords values (438, 'كاد', 'كَادَ', 'فعل', 'كاد و اخواتها', 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 'رافع', 'اسم', '');
insert into classedstopwords values (439, 'كرب', 'كَرِبَ', 'فعل', 'كاد و اخواتها', 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 'رافع', 'اسم', '');
insert into classedstopwords values (440, 'لازالت', 'لَازَالَتْ', 'فعل', 'كاد و اخواتها', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'رافع', 'اسم', '');
insert into classedstopwords values (441, 'هب', 'هَبَّ', 'فعل', 'كاد و اخواتها', 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 'رافع', 'اسم', '');
insert into classedstopwords values (442, 'إنما', 'إِنَّمَا', 'حرف', 'كافة ومكفوفة', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'عاطل', '', '');
insert into classedstopwords values (443, 'لكنما', 'لَكِنَّمَا', 'حرف', 'كافة ومكفوفة', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'عاطل', '', '');
insert into classedstopwords values (444, 'آض', 'آضَ', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 'رافع', 'اسم', '');
insert into classedstopwords values (445, 'أصبح', 'أَصْبَحَ', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 'رافع', 'اسم', '');
insert into classedstopwords values (446, 'أضحى', 'أَضْحَى', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 'رافع', 'اسم', '');
insert into classedstopwords values (447, 'أمسى', 'أَمْسَى', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 'رافع', 'اسم', '');
insert into classedstopwords values (448, 'ارتد', 'اِرْتَدَّ', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 'رافع', 'اسم', '');
insert into classedstopwords values (449, 'استحال', 'اِسْتَحَالَ', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 'رافع', 'اسم', '');
insert into classedstopwords values (450, 'انقلب', 'اِنْقَلَبَ', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 'رافع', 'اسم', '');
insert into classedstopwords values (451, 'بات', 'بَاتَ', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 'رافع', 'اسم', '');
insert into classedstopwords values (452, 'تبدل', 'تَبَدَّلَ', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 'رافع', 'اسم', '');
insert into classedstopwords values (453, 'تحول', 'تَحَوَّلَ', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 'رافع', 'اسم', '');
insert into classedstopwords values (454, 'حار', 'حَارَ', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 'رافع', 'اسم', '');
insert into classedstopwords values (455, 'راح', 'رَاحَ', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 'رافع', 'اسم', '');
insert into classedstopwords values (456, 'رجع', 'رَجَعَ', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 'رافع', 'اسم', '');
insert into classedstopwords values (457, 'صار', 'صَارَ', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 'رافع', 'اسم', '');
insert into classedstopwords values (458, 'ظل', 'ظَلَّ', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 'رافع', 'اسم', '');
insert into classedstopwords values (459, 'عاد', 'عَادَ', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 'رافع', 'اسم', '');
insert into classedstopwords values (460, 'غدا', 'غَدَا', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 'رافع', 'اسم', '');
insert into classedstopwords values (461, 'كان', 'كَانَ', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 'رافع', 'اسم', '');
insert into classedstopwords values (462, 'لست', 'لَسْتَ', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 'رافع', 'اسم', '');
insert into classedstopwords values (463, 'لست', 'لَسْتُ', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 'رافع', 'اسم', '');
insert into classedstopwords values (464, 'لست', 'لَسْتِ', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 'رافع', 'اسم', '');
insert into classedstopwords values (465, 'لستم', 'لَسْتُم', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 'رافع', 'اسم', '');
insert into classedstopwords values (466, 'لستما', 'لَسْتُمَا', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 'رافع', 'اسم', '');
insert into classedstopwords values (467, 'لستن', 'لَسْتُنَّ', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 'رافع', 'اسم', '');
insert into classedstopwords values (468, 'لسن', 'لَسْنَ', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 'رافع', 'اسم', '');
insert into classedstopwords values (469, 'لسنا', 'لَسْنَا', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 'رافع', 'اسم', '');
insert into classedstopwords values (470, 'ليس', 'لَيْسَ', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 'رافع', 'اسم', '');
insert into classedstopwords values (471, 'ليسا', 'لَيْسَا', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 'رافع', 'اسم', '');
insert into classedstopwords values (472, 'ليست', 'لَيْسَتْ', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 'رافع', 'اسم', '');
insert into classedstopwords values (473, 'ليستا', 'لَيْسَتَا', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 'رافع', 'اسم', '');
insert into classedstopwords values (474, 'ليسوا', 'لَيْسُوا', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 'رافع', 'اسم', '');
insert into classedstopwords values (475, 'ماانفك', 'مَااِنْفَكَّ', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 'رافع', 'اسم', '');
insert into classedstopwords values (476, 'مابرح', 'مَابَرِحَ', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 'رافع', 'اسم', '');
insert into classedstopwords values (477, 'مادام', 'مَادَامَ', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 'رافع', 'اسم', '');
insert into classedstopwords values (478, 'مازال', 'مَازَالَ', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 'رافع', 'اسم', '');
insert into classedstopwords values (479, 'مافتئ', 'مَافَتِئَ', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 'رافع', 'اسم', '');
insert into classedstopwords values (480, 'بضع', 'بِضْعَ', 'اسم', 'كناية', 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (481, 'ذيت', 'ذَيْتَ', 'اسم', 'كناية', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (482, 'فلان', 'فُلَانٌ', 'اسم', 'كناية', 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (483, 'كأي', 'كَأَيٍّ', 'اسم', 'كناية', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (484, 'كأين', 'كَأَيَّنَ', 'اسم', 'كناية', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (485, 'كأين', 'كَأَيْنَ', 'اسم', 'كناية', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (486, 'كذا', 'كَذَا', 'اسم', 'كناية', 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (487, 'كم', 'كَمْ', 'اسم', 'كناية', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (488, 'كيت', 'كَيْتَ', 'اسم', 'كناية', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (489, 'لا', 'لَا', 'حرف', 'نافية للجنس', 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (490, 'لا', 'لَا', 'حرف', 'ناهية', 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 'جازم', 'فعل', '');
insert into classedstopwords values (491, 'فقط', 'فَقَطْ', 'حرف', '', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (492, 'و', 'وَ', 'حرف', 'حرف عطف', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'متبع', '', '');
insert into classedstopwords values (493, 'بن', 'بْن', 'اسم', 'وصل الأعلام', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'جار', 'اسم', '');
insert into classedstopwords values (494, 'إلا', 'إِلَّا', 'حرف', 'حرف استثناء', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', 'اسم', '');
insert into classedstopwords values (495, 'أيضا', 'أَيْضًا', 'اسم', 'توكيد', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'عاطل', '', '');
insert into classedstopwords values (496, 'بينما', 'بَيْنَمَا', 'اسم', 'ظرف زمان', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'عاطل', '', '');
insert into classedstopwords values (497, 'لا', 'لَا', 'حرف', 'نافية', 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 'رافع', 'فعل', '');
insert into classedstopwords values (498, 'جدا', 'جِدًّا', 'اسم', 'توكيد', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'عاطل', '', '');
insert into classedstopwords values (499, 'حينما', 'حِينَمَا', 'اسم', 'ظرف زمان', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'عاطل', '', '');
insert into classedstopwords values (500, 'مثلما', 'مِثْلَمَا', 'اسم', 'جار ومجرور', 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 'عاطل', '', '');
insert into classedstopwords values (501, 'حسبما', 'حَسْبَمَا', 'اسم', 'جار ومجرور', 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 'عاطل', '', '');
insert into classedstopwords values (502, 'آنذاك', 'آنَذَاكَ', 'اسم', 'ظرف زمان', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'عاطل', '', '');
insert into classedstopwords values (503, 'آنئذ', 'آنَئِذٍ', 'اسم', 'ظرف زمان', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'عاطل', '', '');
insert into classedstopwords values (504, 'أية', 'أَيَّةُ', 'اسم', 'اسم إضافة', 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 'جار', 'اسم', '');
insert into classedstopwords values (505, 'وراءك', 'وَرَاءَكِ', 'اسم فعل', 'اسم فعل', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (506, 'وراءكما', 'وَرَاءَكُما', 'اسم فعل', 'اسم فعل', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (507, 'وراءكم', 'وَرَاءَكُمْ', 'اسم فعل', 'اسم فعل', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (508, 'وراءكن', 'وَرَاءَكُنَّ', 'اسم فعل', 'اسم فعل', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (509, 'وراء', 'وَرَاءَ', 'اسم', 'ظرف مكان', 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 'جار', 'اسم', '');
insert into classedstopwords values (510, 'بعدما', 'بَعْدَمَا', 'اسم', 'ظرف زمان', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'عاطل', '', '');
insert into classedstopwords values (511, 'بئسما', 'بِئْسَمَا', 'اسم فعل', 'المدح والذم', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'عاطل', '', '');
insert into classedstopwords values (512, 'قبلما', 'قَبْلَمَا', 'اسم', 'ظرف زمان', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'عاطل', '', '');
insert into classedstopwords values (513, 'بعدئذ', 'بَعْدَئِذٍ', 'اسم', 'ظرف زمان', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'عاطل', '', '');
insert into classedstopwords values (514, 'حينئذ', 'حِينَئِذٍ', 'اسم', 'ظرف زمان', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'عاطل', '', '');
insert into classedstopwords values (515, 'عندئذ', 'عِنْدَئِذٍ', 'اسم', 'ظرف زمان', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'عاطل', '', '');
insert into classedstopwords values (516, 'إنا', 'إِنَّا', 'حرف', 'ناصب ومنصوب', 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 'عاطل', '', '');
insert into classedstopwords values (517, 'أنا', 'أَنَّا', 'حرف', 'ناصب ومنصوب', 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 'عاطل', '', '');
insert into classedstopwords values (518, 'هاذين', 'هَاذَيْنِ', 'اسم', 'اسم إشارة', 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, '', '', '');
insert into classedstopwords values (519, 'لازال', 'لَازَالَ', 'فعل', 'كاد و اخواتها', 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 'رافع', 'اسم', '');
insert into classedstopwords values (520, 'لازالت', 'لَازَالَتْ', 'فعل', 'كاد و اخواتها', 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 'رافع', 'اسم', '');
insert into classedstopwords values (521, 'لازلت', 'لَازِلْتُ', 'فعل', 'كاد و اخواتها', 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 'ناصب', 'اسم', '');
insert into classedstopwords values (522, 'لازلنا', 'لَازِلْنَا', 'فعل', 'كاد و اخواتها', 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 'ناصب', 'اسم', '');
insert into classedstopwords values (523, 'لازلت', 'لَازِلْتَ', 'فعل', 'كاد و اخواتها', 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 'ناصب', 'اسم', '');
insert into classedstopwords values (524, 'لازلت', 'لَازِلْتِ', 'فعل', 'كاد و اخواتها', 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 'ناصب', 'اسم', '');
insert into classedstopwords values (525, 'لازلتما', 'لَازِلْتُمَا', 'فعل', 'كاد و اخواتها', 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 'ناصب', 'اسم', '');
insert into classedstopwords values (526, 'لازلتما', 'لَازِلْتُمَا', 'فعل', 'كاد و اخواتها', 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 'ناصب', 'اسم', '');
insert into classedstopwords values (527, 'لازلتم', 'لَازِلْتُم', 'فعل', 'كاد و اخواتها', 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 'ناصب', 'اسم', '');
insert into classedstopwords values (528, 'لازلتن', 'لَازِلْتُنَّ', 'فعل', 'كاد و اخواتها', 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 'ناصب', 'اسم', '');
insert into classedstopwords values (529, 'لازالا', 'لَازَالَا', 'فعل', 'كاد و اخواتها', 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 'ناصب', 'اسم', '');
insert into classedstopwords values (530, 'لازالتا', 'لَازَالَتَا', 'فعل', 'كاد و اخواتها', 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 'ناصب', 'اسم', '');
insert into classedstopwords values (531, 'لازالوا', 'لَازَالُوا', 'فعل', 'كاد و اخواتها', 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 'ناصب', 'اسم', '');
insert into classedstopwords values (532, 'لازلن', 'لَازِلْنَ', 'فعل', 'كاد و اخواتها', 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 'ناصب', 'اسم', '');
insert into classedstopwords values (533, 'مازلت', 'مَازِلْتُ', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'ناصب', 'اسم', '');
insert into classedstopwords values (534, 'مازلنا', 'مَازِلْنَا', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'ناصب', 'اسم', '');
insert into classedstopwords values (535, 'مازلت', 'مَازِلْتَ', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'ناصب', 'اسم', '');
insert into classedstopwords values (536, 'مازلت', 'مَازِلْتِ', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'ناصب', 'اسم', '');
insert into classedstopwords values (537, 'مازلتما', 'مَازِلْتُمَا', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'ناصب', 'اسم', '');
insert into classedstopwords values (538, 'مازلتما', 'مَازِلْتُمَا', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'ناصب', 'اسم', '');
insert into classedstopwords values (539, 'مازلتم', 'مَازِلْتُم', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'ناصب', 'اسم', '');
insert into classedstopwords values (540, 'مازلتن', 'مَازِلْتُنَّ', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'ناصب', 'اسم', '');
insert into classedstopwords values (541, 'مازالا', 'مَازَالَا', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'ناصب', 'اسم', '');
insert into classedstopwords values (542, 'مازالتا', 'مَازَالَتَا', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'ناصب', 'اسم', '');
insert into classedstopwords values (543, 'مازالوا', 'مَازَالُوا', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'ناصب', 'اسم', '');
insert into classedstopwords values (544, 'مازلن', 'مَازِلْنَ', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'ناصب', 'اسم', '');
insert into classedstopwords values (545, 'مادمت', 'مَادُمْتُ', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'ناصب', 'اسم', '');
insert into classedstopwords values (546, 'مادمنا', 'مَادُمْنَا', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'ناصب', 'اسم', '');
insert into classedstopwords values (547, 'مادمت', 'مَادُمْتَ', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'ناصب', 'اسم', '');
insert into classedstopwords values (548, 'مادمت', 'مَادُمْتِ', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'ناصب', 'اسم', '');
insert into classedstopwords values (549, 'مادمتما', 'مَادُمْتُمَا', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'ناصب', 'اسم', '');
insert into classedstopwords values (550, 'مادمتما', 'مَادُمْتُمَا', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'ناصب', 'اسم', '');
insert into classedstopwords values (551, 'مادمتم', 'مَادُمْتُم', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'ناصب', 'اسم', '');
insert into classedstopwords values (552, 'مادمتن', 'مَادُمْتُنَّ', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'ناصب', 'اسم', '');
insert into classedstopwords values (553, 'مادامت', 'مَادَامَتْ', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'رافع', 'اسم', '');
insert into classedstopwords values (554, 'ماداما', 'مَادَامَا', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'ناصب', 'اسم', '');
insert into classedstopwords values (555, 'مادامتا', 'مَادَامَتَا', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'ناصب', 'اسم', '');
insert into classedstopwords values (556, 'ماداموا', 'مَادَامُوا', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'ناصب', 'اسم', '');
insert into classedstopwords values (557, 'مادمن', 'مَادُمْنَ', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'ناصب', 'اسم', '');
insert into classedstopwords values (558, 'مابرحت', 'مَابَرِحْتُ', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'ناصب', 'اسم', '');
insert into classedstopwords values (559, 'مابرحنا', 'مَابَرِحْنَا', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'ناصب', 'اسم', '');
insert into classedstopwords values (560, 'مابرحت', 'مَابَرِحْتَ', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'ناصب', 'اسم', '');
insert into classedstopwords values (561, 'مابرحت', 'مَابَرِحْتِ', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'ناصب', 'اسم', '');
insert into classedstopwords values (562, 'مابرحتما', 'مَابَرِحْتُمَا', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'ناصب', 'اسم', '');
insert into classedstopwords values (563, 'مابرحتما', 'مَابَرِحْتُمَا', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'ناصب', 'اسم', '');
insert into classedstopwords values (564, 'مابرحتم', 'مَابَرِحْتُم', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'ناصب', 'اسم', '');
insert into classedstopwords values (565, 'مابرحتن', 'مَابَرِحْتُنَّ', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'ناصب', 'اسم', '');
insert into classedstopwords values (566, 'مابرحت', 'مَابَرِحَتْ', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'رافع', 'اسم', '');
insert into classedstopwords values (567, 'مابرحا', 'مَابَرِحَا', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'ناصب', 'اسم', '');
insert into classedstopwords values (568, 'مابرحتا', 'مَابَرِحَتَا', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'ناصب', 'اسم', '');
insert into classedstopwords values (569, 'مابرحوا', 'مَابَرِحُوا', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'ناصب', 'اسم', '');
insert into classedstopwords values (570, 'مابرحن', 'مَابَرِحْنَ', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'ناصب', 'اسم', '');
insert into classedstopwords values (571, 'مافتئت', 'مَافَتِئْتُ', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'ناصب', 'اسم', '');
insert into classedstopwords values (572, 'مافتئنا', 'مَافَتِئْنَا', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'ناصب', 'اسم', '');
insert into classedstopwords values (573, 'مافتئت', 'مَافَتِئْتَ', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'رافع', 'اسم', '');
insert into classedstopwords values (574, 'مافتئت', 'مَافَتِئْتِ', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'ناصب', 'اسم', '');
insert into classedstopwords values (575, 'مافتئتما', 'مَافَتِئْتُمَا', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'ناصب', 'اسم', '');
insert into classedstopwords values (576, 'مافتئتما', 'مَافَتِئْتُمَا', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'ناصب', 'اسم', '');
insert into classedstopwords values (577, 'مافتئتم', 'مَافَتِئْتُم', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'ناصب', 'اسم', '');
insert into classedstopwords values (578, 'مافتئتن', 'مَافَتِئْتُنَّ', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'ناصب', 'اسم', '');
insert into classedstopwords values (579, 'مافتئت', 'مَافَتِئَتْ', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'رافع', 'اسم', '');
insert into classedstopwords values (580, 'مافتئا', 'مَافَتِئَا', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'ناصب', 'اسم', '');
insert into classedstopwords values (581, 'مافتئتا', 'مَافَتِئَتَا', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'ناصب', 'اسم', '');
insert into classedstopwords values (582, 'مافتئوا', 'مَافَتِئُوا', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'ناصب', 'اسم', '');
insert into classedstopwords values (583, 'مافتئن', 'مَافَتِئْنَ', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'ناصب', 'اسم', '');
insert into classedstopwords values (584, 'ماانفككت', 'مَااِنْفَكَكْتُ', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'ناصب', 'اسم', '');
insert into classedstopwords values (585, 'ماانفككنا', 'مَااِنْفَكَكْنَا', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'ناصب', 'اسم', '');
insert into classedstopwords values (586, 'ماانفككت', 'مَااِنْفَكَكْتَ', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'ناصب', 'اسم', '');
insert into classedstopwords values (587, 'ماانفككت', 'مَااِنْفَكَكْتِ', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'ناصب', 'اسم', '');
insert into classedstopwords values (588, 'ماانفككتما', 'مَااِنْفَكَكْتُمَا', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'ناصب', 'اسم', '');
insert into classedstopwords values (589, 'ماانفككتما', 'مَااِنْفَكَكْتُمَا', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'ناصب', 'اسم', '');
insert into classedstopwords values (590, 'ماانفككتم', 'مَااِنْفَكَكْتُم', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'ناصب', 'اسم', '');
insert into classedstopwords values (591, 'ماانفككتن', 'مَااِنْفَكَكْتُنَّ', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'ناصب', 'اسم', '');
insert into classedstopwords values (592, 'ماانفكت', 'مَااِنْفَكَّتْ', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'رافع', 'اسم', '');
insert into classedstopwords values (593, 'ماانفكا', 'مَااِنْفَكَّا', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'ناصب', 'اسم', '');
insert into classedstopwords values (594, 'ماانفكتا', 'مَااِنْفَكَّتَا', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'ناصب', 'اسم', '');
insert into classedstopwords values (595, 'ماانفكوا', 'مَااِنْفَكُّوا', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'ناصب', 'اسم', '');
insert into classedstopwords values (596, 'ماانفككن', 'مَااِنْفَكَكْنَ', 'فعل', 'كان و أخواتها', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'ناصب', 'اسم', '');
